name: Build_armv7-immortal

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    concurrency:
      group: build-armv7-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Debug config hash input
      run: |
        ls -lh armv7.config || echo "armv7.config not found"
        echo "Hash: ${{ hashFiles('armv7.config') }}"

    - name: Restore build cache
      uses: actions/cache@v3
      with:
        path: |
          immortalwrt/tmp
          immortalwrt/staging_dir
          immortalwrt/dl
        key: build-armv7-${{ runner.os }}-${{ hashFiles('armv7.config') }}
        restore-keys: |
          build-armv7-${{ runner.os }}-
          build-armv7-

    - name: Init build environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set -ex
        sudo rm -rf \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo apt install -y qemu-utils upx-ucl uuid-dev

    - name: Clone ImmortalWrt
      env:
        REPO_URL: https://github.com/immortalwrt/immortalwrt
        REPO_BRANCH: master
      run: |
        git clone -b $REPO_BRANCH --single-branch --filter=blob:none $REPO_URL immortalwrt
        cd immortalwrt
        echo "src-git helloworld https://github.com/fw876/helloworld.git" >> ./feeds.conf.default

    # - name: Customize plugins
    #   working-directory: ./immortalwrt
    #   run: |
    #     git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
    #     git clone https://github.com/gdy666/luci-app-lucky.git package/lucky

    - name: Update feeds
      working-directory: ./immortalwrt
      run: |
        sed -i '$a src-git smpackage https://github.com/kenzok8/small-package' feeds.conf.default
        sed -i '$a src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main' feeds.conf.default
        sed -i '$a src-git passwall_luci https://github.com/xiaorouji/openwrt-passwall.git;main' feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds update -a
        ./scripts/feeds install -a        

    - name: Apply configuration
      working-directory: ./immortalwrt
      run: |
        [ -e ../armv7.config ] && cp ../armv7.config .config
        [ -f ./customize.sh ] && chmod +x ./customize.sh && ./customize.sh
        make defconfig

    - name: Download packages
      working-directory: ./immortalwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      working-directory: ./immortalwrt
      run: |
        echo "Building with $(nproc) threads"
        make -j$(($(nproc)+1)) V=s

    - name: Save build cache
      uses: actions/cache@v3
      with:
        path: |
          immortalwrt/tmp
          immortalwrt/staging_dir
          immortalwrt/dl
        key: build-armv7-${{ runner.os }}-${{ hashFiles('armv7.config') }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt_armv7
        path: immortalwrt/bin/targets/*/*
        retention-days: 3

    # ✅ 可选：构建成功通知
    # - name: Notify success
